#!/usr/bin/python3
import subprocess
import sys
import re


command_result = subprocess.run(
    ["nvidia-smi", "-q", "-g", "0", "-d", "UTILIZATION"],
    stdout=subprocess.PIPE
)
splitlined = command_result.stdout.decode().splitlines()
striped = [s.replace(" ", "") for s in splitlined]
find_gpu_line = list(filter(lambda line: line.startswith("Gpu:"), striped)).pop(0)
get_gpu_percentage = re.search(r"Gpu:(\d*)%", find_gpu_line)

sys.stdout.write(get_gpu_percentage.group(1) if get_gpu_percentage else "-")
